spring:
  datasource:
    url: jdbc:mysql://db-clouds.cdaayyuqcutk.eu-north-1.rds.amazonaws.com:3306/test?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    #show-sql: true
    hibernate:
      ddl-auto: update
  #banner:
    #location: classpath:banner.txt

  #mvc:
    #path match:
      #matching-strategy: ant_path_matcher

#server:
  #port: 8080